# Generated by Django 5.1.7 on 2025-03-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_consultant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="disease/"),
        ),
    ]
