# Generated by Django 5.1.7 on 2025-03-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_consultant_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.consultant"
                    ),
                ),
            ],
        ),
    ]
