# Generated by Django 5.1.7 on 2025-03-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_solution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.consultant",
            ),
        ),
    ]
