# Generated by Django 5.1.7 on 2025-03-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_consultant_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.consultant"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
