# Generated by Django 5.1.7 on 2025-03-13 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_consultant_name_alter_solution_consultant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="image",
            field=models.ImageField(default=2, upload_to="disease/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consultant",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
