# Generated by Django 5.1.7 on 2025-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(default=100, editable=False),
        ),
    ]
