# Generated by Django 5.1.7 on 2025-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_doctor_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="visited",
            field=models.BooleanField(default=False),
        ),
    ]
